#pragma once


#define TXD_HC32_PIN_NUM GPIO_NUM_1
#define RXD_HC32_PIN_NUM GPIO_NUM_2
#define HC32_UART_NUM UART_NUM_1
#define HC32_UART_BAUDRATE 115200

#define KEY_INPUT_PIN_NUM GPIO_NUM_39
#define USB_INPUT_PIN_NUM GPIO_NUM_38

#define ESP_PRINT_PIN_NUM GPIO_NUM_46
#define PWM_MOTOR_PIN_NUM GPIO_NUM_47

#define I2C_SENSORS_SDA_PIN_NUM GPIO_NUM_18
#define I2C_SENSORS_SCL_PIN_NUM GPIO_NUM_19

#define INT1_LSM_PIN_NUM GPIO_NUM_20
#define INT2_LSM_PIN_NUM GPIO_NUM_21

#define ESP_PRINT_PIN_NUM GPIO_NUM_46
// #define ESP_STA_PIN_NUM

#define LCD_PIN_NUM_PWM_BL GPIO_NUM_45
#define LCD_PIN_NUM_EN    GPIO_NUM_41
#define LCD_PIN_NUM_CLK   GPIO_NUM_7
#define LCD_PIN_NUM_RST   GPIO_NUM_8
#define LCD_PIN_NUM_CS    GPIO_NUM_14
#define LCD_PIN_NUM_DC    GPIO_NUM_13
#define LCD_PIN_NUM_DATA0 GPIO_NUM_6
#define LCD_PIN_NUM_DATA1 GPIO_NUM_12
#define LCD_PIN_NUM_DATA2 GPIO_NUM_5
#define LCD_PIN_NUM_DATA3 GPIO_NUM_11
#define LCD_PIN_NUM_DATA4 GPIO_NUM_4
#define LCD_PIN_NUM_DATA5 GPIO_NUM_10
#define LCD_PIN_NUM_DATA6 GPIO_NUM_3
#define LCD_PIN_NUM_DATA7 GPIO_NUM_9
// #define LCD_PIN_NUM_TE 

#define TP_PIN_NUM_SDA    GPIO_NUM_15
#define TP_PIN_NUM_SCL    GPIO_NUM_16
#define TP_PIN_NUM_INT    GPIO_NUM_17